name: firebase_package
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.6.0
  equatable: ^2.0.5
  firebase_auth: ^4.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

